# AWS sub-providers batch 1

# AWS sub-providers
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-acm
spec:
  package: xpkg.upbound.io/upbound/provider-aws-acm:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-acmpca
spec:
  package: xpkg.upbound.io/upbound/provider-aws-acmpca:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-amp
spec:
  package: xpkg.upbound.io/upbound/provider-aws-amp:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-apigateway
spec:
  package: xpkg.upbound.io/upbound/provider-aws-apigateway:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-apigatewayv2
spec:
  package: xpkg.upbound.io/upbound/provider-aws-apigatewayv2:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-apprunner
spec:
  package: xpkg.upbound.io/upbound/provider-aws-apprunner:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-appstream
spec:
  package: xpkg.upbound.io/upbound/provider-aws-appstream:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-athena
spec:
  package: xpkg.upbound.io/upbound/provider-aws-athena:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-autoscaling
spec:
  package: xpkg.upbound.io/upbound/provider-aws-autoscaling:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-backup
spec:
  package: xpkg.upbound.io/upbound/provider-aws-backup:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-batch
spec:
  package: xpkg.upbound.io/upbound/provider-aws-batch:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-bedrockagent
spec:
  package: xpkg.upbound.io/upbound/provider-aws-bedrockagent:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-budgets
spec:
  package: xpkg.upbound.io/upbound/provider-aws-budgets:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cloudformation
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cloudformation:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cloudfront
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cloudfront:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cloudsearch
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cloudsearch:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cloudwatch
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cloudwatch:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cloudwatchevents
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cloudwatchevents:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cloudwatchlogs
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cloudwatchlogs:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-codeartifact
spec:
  package: xpkg.upbound.io/upbound/provider-aws-codeartifact:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cognitoidentity
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cognitoidentity:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cognitoidp
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cognitoidp:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-connect
spec:
  package: xpkg.upbound.io/upbound/provider-aws-connect:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cur
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cur:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-datasync
spec:
  package: xpkg.upbound.io/upbound/provider-aws-datasync:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-dax
spec:
  package: xpkg.upbound.io/upbound/provider-aws-dax:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-devicefarm
spec:
  package: xpkg.upbound.io/upbound/provider-aws-devicefarm:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-directconnect
spec:
  package: xpkg.upbound.io/upbound/provider-aws-directconnect:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-dms
spec:
  package: xpkg.upbound.io/upbound/provider-aws-dms:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-docdb
spec:
  package: xpkg.upbound.io/upbound/provider-aws-docdb:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ds
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ds:v2.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-dsql
spec:
  package: xpkg.upbound.io/upbound/provider-aws-dsql:v2.3.0
