project: cluster-whisperer
providers:
  google_secrets_manager:
    kind: google_secretmanager
    maps:
      - id: secrets
        path: projects/demoo-ooclock
        keys:
          # Anthropic API key for LangChain agent
          anthropic-api-key: ANTHROPIC_API_KEY
