# Secrets configuration for vals
# https://github.com/helmfile/vals
#
# Usage:
#   vals eval -f .vals.yaml              # Show resolved values
#   vals exec -f .vals.yaml -- command   # Run command with secrets injected

ANTHROPIC_API_KEY: ref+gcpsecrets://demoo-ooclock/anthropic-api-key
